version: "3.8"

services:
  stripe-cli:
    image: stripe/stripe-cli:latest
    command: listen --api-key ${STRIPE_API_KEY} --forward-to web:8000/stripe/webhook --skip-verify
    volumes:
      - stripe-config:/root/.config/stripe/

  web:
    container_name: platoform_django
    build:
      context: .
      dockerfile: ./services/docker/django/development/Dockerfile
    env_file:
      - .env.development
    networks:
      - platoform_net
    depends_on:
      - db

  frontend:
    container_name: platoform_react
    build:
      context: .
      dockerfile: ./services/docker/react/development/Dockerfile
    env_file:
      - .env.development
    networks:
      - platoform_net
    depends_on:
      - web

  db:
    image: postgres:16-alpine
    container_name: platform_postgres
    restart: unless-stopped
    env_file:
      - .env.development
    networks:
      - platoform_net

volumes:
  static_volume: {}
  postgres_data: {}
  stripe-config: {}

networks:
  platoform_net:
