version: "3.8"

x-app-env: &app-env
  env_file:
    - ./env/.env.development
  networks:
    - platoform_net

services:
  web:
    <<: *app-env
    volumes:
      - static_volume:/app/backend/src/mediafields
      - ./services/backend/htmlcov:/app/backend/htmlcov
      - stripe-secrets:/stripe-secrets
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      stripe-cli:
        condition: service_started
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  frontend:
    <<: *app-env
    volumes:
      - ./services/frontend/src:/app/frontend/src
    ports:
      - "5173:80"
    depends_on:
      - web

  db:
    <<: *app-env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    <<: *app-env
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq:
    <<: *app-env
    ports:
      - "5672:5672"
      - "15672:15672"

  stripe-cli:
    <<: *app-env
    build:
      context: .
      dockerfile: ./services/docker/stripe/development/Dockerfile
    volumes:
      - stripe-config:/root/.config/stripe/
      - stripe-secrets:/stripe-secrets

  celery-worker:
    <<: *app-env
    volumes:
      - static_volume:/app/backend/src/mediafields
      - ./services/backend/htmlcov:/app/backend/htmlcov
      - stripe-secrets:/stripe-secrets
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  celery-beat:
    <<: *app-env
    volumes:
      - static_volume:/app/backend/src/mediafields
      - ./services/backend/htmlcov:/app/backend/htmlcov
      - stripe-secrets:/stripe-secrets
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  flower:
    <<: *app-env
    ports:
      - "5555:5555"
    volumes:
      - static_volume:/app/backend/src/mediafields
      - ./services/backend/htmlcov:/app/backend/htmlcov
    depends_on:
      rabbitmq:
        condition: service_healthy

  prometheus:
    <<: *app-env
    ports:
      - "9090:9090"
    volumes:
      - ./services/docker/django/development/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      web:
        condition: service_healthy

  grafana:
    <<: *app-env
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_healthy

  # sonarqube:
  #   image: sonarqube:lts-community
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
  #     SONAR_JDBC_USERNAME: admin
  #     SONAR_JDBC_PASSWORD: admin
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_logs:/opt/sonarqube/logs
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #   networks:
  #     - platoform_net

volumes:
  static_volume: {}
  postgres_data: {}
  redis_data: {}
  stripe-config: {}
  stripe-secrets: {}
  prometheus_data: {}
  grafana_data: {}
  sonarqube_data: {}
  sonarqube_logs: {}
  sonarqube_extensions: {}
  ollama_data: {}

networks:
  platoform_net:
